### ISSUE TITLE
[node8] infinite recursion loading ip blocklist

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-customs-server#212]
Seen in travis tests: https://travis-ci.org/mozilla/fxa-customs-server/jobs/295538389

SImple demo program:
```
var log = {
  info: function () {
  },
  error: function () {
  },
  trace: function () {
  }
}

var config = {
  ipBlocklist: {
    updatePollInterval: 1, // 1 Second
    logOnlyLists: [
      './test/mocks/logOnlyList.netset'
    ]
  }
}

var IPBlocklist = require('../../lib/ip_blocklist')(log, config)
var IPBlocklistManager = require('../../lib/ip_blocklist_manager')(log, config)

var lists = [
  './test/mocks/firehol_level1.netset',
  './test/mocks/simple.netset'
]

var ipBlocklist = new IPBlocklist()
ipBlocklist.load(lists[0]) // RangeError: Maximum call stack size exceeded
  .then(function () {
    console.log('loaded ok')
  })

ipBlocklist = new IPBlocklistManager()
ipBlocklist.load(lists[0]) // RangeError: Maximum call stack size exceeded
  .then(function () {
    console.log('loaded ok')
  })
```
Output:
```
/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:487
Promise.prototype._settlePromiseFromHandler = function (
                                                       ^

RangeError: Maximum call stack size exceeded
    at Promise._settlePromiseFromHandler (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:487:56)
    at Promise._settlePromise (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:684:18)
```

**Comment by rfk** [comment]
To be clear, is this new behaviour that appears with node8?

**Comment by rfk** [comment]
My first guess would be some change in the semantics of `setImmediate` that is affecting our use of it here:

  https://github.com/mozilla/fxa-customs-server/blob/master/lib/ip_blocklist.js#L95

**Comment by jrgm** [comment]
Yeah. It's new with node 8. See https://travis-ci.org/mozilla/fxa-customs-server/builds/295538387 - node 6 passes; node 8 max stack.

**Comment by vladikoff** [comment]
Blocks node 8 upgrade
